version: '2'
services:

  ticks-api:
    build: .
    container_name: ticks-api
    environment:
      RACK_ENV: development
      DATABASE_URL: "postgres://postgres:@ticks-pg/my_api_development"
      REDIS_URL: "redis://ticks-redis:6379/0"
    depends_on:
      - ticks-pg
      - ticks-redis
    ports:
      - "3000:3000"
    networks:
      - ticks

  ticks-worker:
    build: .
    container_name: ticks-worker
    environment:
      RACK_ENV: development
      DATABASE_URL: "postgres://postgres:@ticks-pg/my_api_development"
      REDIS_URL: "redis://ticks-redis:6379/0"
    depends_on:
      - ticks-pg
      - ticks-redis
    command: bundle exec sidekiq -r ./app.rb
    networks:
      - ticks

  ticks-pg:
    image: postgres:9.4-alpine
    container_name: ticks-postgres
    ports:
      - "5432:5432"
    networks:
      - ticks

  ticks-redis:
    image: redis:3.0.7
    container_name: ticks-redis
    ports:
      - "6379:6379"
    networks:
      - ticks

############################
# networks
############################
networks:
  ticks:
